---
dist: bionic
language: python
cache:
  timeout: 3600
  pip: true
  directories:
    - $HOME/.docker
services:
  - docker

# Distros
_ubuntu_xenial_build: &ubuntu_xenial_build
  docker_image_tag: ubuntu-xenial
  CACHE_NAME: xenial

_ubuntu_bionic_build: &ubuntu_bionic_build
  docker_image_tag: ubuntu-bionic
  CACHE_NAME: bionic

_ubuntu_focal_build: &ubuntu_focal_build
  docker_image_tag: ubuntu-focal
  CACHE_NAME: focal

_centos_build: &centos_build
  docker_image_tag: centos-7
  CACHE_NAME: cent7

# Ansible versions
_ansible_27_build: &ansible_27_build
  ansible_version: "'ansible>=2.7,<2.8'"

_ansible_28_build: &ansible_28_build
  ansible_version: "'ansible>=2.8,<2.9'"

env:
  global:
    - ANSIBLE_FORCE_COLOR=1
    - docker_image=quay.io/loganv/docker-ci
    - docker_command=/lib/systemd/systemd
    - cache_dir=$HOME/.docker
    - ansible_version=ansible

matrix:
  fast_finish: true
  include:
    # ANSIBLE 2.8
    - env:
        <<: *ubuntu_xenial_build
        <<: *ansible_28_build
    - env:
        <<: *ubuntu_bionic_build
        <<: *ansible_28_build
    - env:
        <<: *ubuntu_focal_build
        <<: *ansible_28_build
    - env:
        <<: *centos_build
        <<: *ansible_28_build
    # ANSIBLE STABLE
    - env:
        <<: *ubuntu_xenial_build
    - env:
        <<: *ubuntu_bionic_build
    - env:
        <<: *ubuntu_focal_build
    - env:
        <<: *centos_build

before_install:
  # Load cached docker images
  - if [[ -d ${cache_dir} ]]; then ls ${cache_dir}/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - if [[ -n ${docker_image_tag} ]]; then docker pull ${docker_image}:${docker_image_tag}; fi
install:
  - pip install -r test-requirements.txt ${ansible_version}
script:
  - sudo modprobe ip6table_filter
  - molecule test
before_cache:
  # Save tagged docker images
  - >
    mkdir -p ${cache_dir} && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e ${cache_dir}/$1.tar.gz || docker save $0 | gzip -2 > ${cache_dir}/$1.tar.gz'
notifications:
  email: false
  slack:
    rooms:
      secure: JQFhp5a02z7PAylWncJISi7DDIqbu8B1EewqB6lkiGO8R7wsNbJ+2Ofjw/1ThxL2XGlAnY/QsZu2v389x3ZgGpeGwpnpy0jNgx3OyyxUUagcKGh46/tysOlFTDtbYvMxFEK7fwInfQkBqYE/pe3dSUKc3M8E0wE0D6vhwepNgD55kyHmgrCB8MEvBoVe0sYAKxmg4/UkYaLhNGIv4UwkDJPNx5LW/Cak+ghaRZdfhu91tjUYDkEBYFVvz2XYRNFYnVDdSrQta4VsNArMW/n4y/Gb8h1JHI98MPV+h/+sSLH3z1u0pbOpPR9/xn8oLBnZ6gVrqqAU1UDm1tNZmrLoWHGJz253lz+ftAwJXm4jpzb5bFfMQmNMyh05rY8VStZ6vMuMUY+Vpxc8ASKevTGq4nfTvdLhjKO95Q5CMkYdG21IHva+gc2+ZaRek0efaTCCAFWUp5qSVo0pQAUz5m0/+dSFak+/jd7vjaiCDgua1opOBa2yrKXTQ2CUqTUfUtfkMgDiGKa2OdySbdg02ji4rz6RvHLjJdsQgsFB5jWk0w8ZEiauWj5ViJJJwRl82bKxVR2vFCrhIR6Hk5KOtA94ZlvAltWyb4ykkoG17phXWRfJ7LeHxg0jgxQlN4afEj5g6uytJO4BaLuQ8r3C22cxMnD/F4XCaZCJxhLwsGCZ/Vc=
