---
lint: |
  set -e
  yamllint .
  ansible-lint -vv --exclude=.tox --exclude=molecule/default/converge.yml -x 204,208
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  options:
    v: True
  log: True
  config_options:
    defaults:
      inject_facts_as_vars: false
platforms:
  - name: iptables
    image: "${docker_user:-quay.io/gotmax23}/${docker_image_tag:-ubuntu-systemd:jammy}"
    command: ""
    pre_build_image: true
    groups:
      - all
    privileged: true
