---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${docker_image:-quay.io/loganv/docker-ci}:${docker_image_tag:-ubuntu-focal}"
    user: root
    command: ${docker_command:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
lint: |
  set -e
  yamllint .
provisioner:
  name: ansible
verifier:
  name: ansible
